# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy source files
COPY pyproject.toml setup.py ./
COPY src ./src

# Copy any package data (e.g., README, .env example)
COPY README.md .
COPY .env.example .env

# Install the package with image extras
RUN pip install --no-cache-dir .[image]

# Ensure entrypoint is executable
ENTRYPOINT ["mcp-imageserve", "stdio"]
